#!/bin/bash

echo "🔧 First Media Admin System Setup"
echo "================================="

# Make all bash scripts executable
echo "📝 Making scripts executable..."
chmod +x *.sh

echo ""
echo "✅ Setup complete!"
echo ""
echo "📋 Prerequisites:"
echo "  • Node.js (v14 or higher)"
echo "  • npm (comes with Node.js)"
echo ""
echo "🚀 To start the system:"
echo "  ./start-unified.sh"
echo ""
echo "🌐 Available URLs (after starting):"
echo "  🔐 Login Page (Main): http://localhost:3000/auth.html"
echo "  📊 Admin Panel: http://localhost:3000/admin"
echo "  🏠 Old Home Page: http://localhost:3000/Login.html"
echo "  📱 Dashboard: http://localhost:3000/dashboard.html"
echo "  💾 Database: SQLite (data/user_data.db)"
echo ""
echo "📝 Features:"
echo "  ✅ SQLite database storage"
echo "  ✅ Real-time data collection"
echo "  ✅ Search and filter functionality"
echo "  ✅ Export to CSV/JSON"
echo "  ✅ Admin panel with statistics"
echo "  ✅ Social login (Google, Facebook, Instagram)"
echo ""
echo "💡 Tips:"
echo "  • All user data is stored in SQLite database"
echo "  • Admin panel shows real-time statistics"
echo "  • Data can be exported in CSV or JSON format"
echo "  • Server auto-restarts on file changes"
echo "" 